apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trondelagfylke-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/instance: fint-samtykke-service-backend_trondelagfylke-no
  fintlabs.no/org-id: trondelagfylke-no

patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "trondelagfylke.no"
    target:
      kind: FintClient
      name: samtykke-srv-be-client
  - patch: |-
      - op: replace
        path: "/spec/url/basePath"
        value: "/trondelagfylke-no/consents"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/trondelagfylke-no/consents"
      - op: replace
        path: "/spec/env/0/value"
        value: "trondelagfylke.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "https://role-catalog.vigoiks.no/vigo/samtykke/user"
      - op: replace
        path: "/spec/env/2/value"
        value: "https://api.felleskomponent.no"
      - op: replace
        path: "/spec/env/3/value"
        value: "https://api.felleskomponent.no/"

    target:
      kind: Application
      name: fint-samtykke-service-backend

