fint:
  org-id: fintlabs.no
  client:
    registration-id: fint
    password: ${fint.core.oauth2.password}
    username: ${fint.core.oauth2.username}
    base-url: https://beta.felleskomponent.no
  integration:
    service:
      authorized-role: https://role-catalog.vigoiks.no/vigo/samtykke/user
      authorized-org-id: vigo.no


  concent:
    endpoints:
      baseUri: https://beta.felleskomponent.no/
      employeeUri: administrasjon/personal/personalressurs/ansattnummer/
      employeessnUri: administrasjon/personal/person/fodselsnummer/
      studentUri: utdanning/elev/elev/elevnummer/
      studentssnUri: utdanning/elev/person/fodselsnummer/
      consentUri: personvern/samtykke/samtykke/
      processorsUri: personvern/samtykke/tjeneste/
      processorUri: personvern/samtykke/tjeneste/systemid/
      processingUri: personvern/samtykke/behandling/
      processingbaseUri: personvern/kodeverk/behandlingsgrunnlag/systemid/
      personaldataUri: personvern/kodeverk/personopplysning/systemid/

  branding:
    logo: company-logo.png
    primaryColor: 7a1668
    primaryColorLight: 513f35
    secondaryColor: 513f35
    featureColor1: 0b8797
    featureColor2: d0eaed
    phoneNumber: 11223344
    mail: postatvigoiks.no
    countyName: Vigo IKS


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            client-id: ${fint.core.oauth2.client-id}
            client-secret: ${fint.core.oauth2.client-secret}
            provider: fint-idp
            scope: fint-client

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    no.fintlabs: debug


