fint:
  org-id: fintlabs.no
  client:
    registration-id: fint
    password: ${fint.core.oauth2.password}
    username: ${fint.core.oauth2.username}
    base-url: https://beta.felleskomponent.no
  integration:
    service:
      authorized-role: https://role-catalog.vigoiks.no/vigo/samtykke/user


spring:
  webflux:
    base-path: /consents
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            client-id: ${fint.core.oauth2.client-id}
            client-secret: ${fint.core.oauth2.client-secret}
            provider: fint-idp
            scope: fint-client