apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rogfk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/instance: vigobas-samtykke-backend_rogfk_no
  fintlabs.no/org-id: rogfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "rogfk.no"
    target:
      kind: FintClient
      name: vigobas-samtykke-backend-fint-client
  - patch: |-
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/rogfk-no/api"
    target:
      kind: Application
      name: vigobas-samtykke-backend